O Catch segura e analisa as exceções lançadas pelo programa. Após o catch, o programa continua normalmente. 